#!/bin/sh

# Set battery levels
WARNING_LEVEL=25
CRITICAL_LEVEL=10

# Set file to save battery status
battery_file=/tmp/battery-notify

# Send notification
send_notification() {
    notify-send "$status battery: ${capacity}%" -i "${icon}" -r 10001 -u "${urgency}"
}

# Write status to file
write_status() {
    echo "$status" > "$battery_file"
}

# Do nothing if status is the same as file
compare_status() {
    [ ! -f "$battery_file" ] || [ "$status" != "$(cat "$battery_file")" ]
}

# Set icon name based on battery capacity
# And set notification urgency level
get_icon() {
    if [ "$capacity" -gt "$WARNING_LEVEL" ]; then
        icon="battery-good"
        urgency="normal"
    elif [ "$capacity" -gt "$CRITICAL_LEVEL" ]; then
        icon="battery-low"
        urgency="critical"
    else
        icon="battery-caution"
        urgency="critical"
    fi
}

# Get battery capacity of first occurrence
capacity="$(cat /sys/class/power_supply/BAT?/capacity | head -n 1)"
# Get battery status of first occurrence
status="$(cat /sys/class/power_supply/BAT?/status | head -n 1)"

# Match battery status
case $status in
    Full)
        # Change icon and urgency level for status
        compare_status && icon="battery-full-charged" urgency="low" send_notification && write_status
        ;;
    Charging)
        # Append status to icon and change urgency level for status
        compare_status && get_icon && icon="${icon}-charging" urgency="normal" send_notification && write_status
        ;;
    Discharging)
        # Set status as icon to send notifications at different battery levels
        get_icon && status="$icon" compare_status && send_notification && status="$icon" write_status
        ;;
esac
